### ISSUE TITLE
PRATO-13 Automatic Builds per branch

### ISSUE THREAD

**Issue by kapraran** [chrisdd2/pratolog#13]
As a developer, I want the application codebase to automatically trigger builds for each branch in the version control system, ensuring that stakeholders can easily access and test the latest changes, improving collaboration and feedback cycles.

**Comment by chrisdd2** [comment]
Implemented as an action for every commit
Example commit in non main branch [https://github.com/chrisdd2/pratolog/actions/runs/6707151615](https://github.com/chrisdd2/pratolog/actions/runs/6707151615)

**Comment by kapraran** [comment]
Thanks, good job 👍
